# Generated by Django 2.0 on 2019-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.IntegerField()),
                ('billingAddress', models.TextField()),
                ('shippingAddress', models.TextField()),
                ('creditStanding', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
