# Generated by Django 2.0 on 2019-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('productId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CANCEL', 'Cancelled'), ('COMPLETE', 'Completed'), ('SHIP', 'Shipped'), ('PAY', 'Paid')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusChangedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
